catalogs:
  build:
    vite-plus: ^0.1.18
  types:
    '@types/node': ^25.6.0
    typescript: ^5.9.3
  lint:
    '@oxlint/plugins': ^1.60.0
    oxlint: ^1.60.0
  prod:
    pathe: ^2.0.3
  dev:
    bumpp: ^11.0.1
